name: Docs2Pages
on:
  push:
    #tags: '*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
          version: 1.4.0
          virtualenvs-create: true
          virtualenvs-in-project: true

    - name: Disable experimental installer
      run: poetry config experimental.new-installer false

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: poetry install --with docs --no-interaction

    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        poetry run sphinx-build -b html . build
        cp -r build/* ../gh-pages/        
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4
      with:
        branch: gh-pages
        folder: gh-pages